### ISSUE TITLE
 📳RangeError (index): Invalid value: Not in inclusive range 0..26: 30 👀

### ISSUE THREAD

**Issue by Lakhankumawat** [SphericalKat/dart-fuzzywuzzy#6] opened 2021-09-29 04:51 UTC
# Error 🙄
```
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building _SearchPage<String>(dirty, dependencies: [_LocalizationsScope-[GlobalKey#e1ca9], _InheritedTheme], state: _SearchPageState<String>#62f97):
RangeError (index): Invalid value: Not in inclusive range 0..26: 30

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///F:/Marketing-App/lib/main.dart:8:10
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      DiffUtils.levEditDistance (package:fuzzywuzzy/diffutils/diff_utils.dart:600:37)
#2      DiffUtils.getRatio (package:fuzzywuzzy/diffutils/diff_utils.dart:732:24)
#3      SimpleRatio.apply (package:fuzzywuzzy/ratios/simple_ratio.dart:7:29)
#4      ratio (package:fuzzywuzzy/fuzzywuzzy.dart:14:24)
#5      WeightedRatio.apply (package:fuzzywuzzy/algorithms/weighted_ratio.dart:26:16)
#6      Extractor.extractWithoutOrder (package:fuzzywuzzy/extractor.dart:27:24)
#7      extractAll (package:fuzzywuzzy/fuzzywuzzy.dart:94:20)

```

# My FuzzyWuzzy Implementation
```
List<String> testing =
          extractAll(query: query, choices: suggestions, cutoff: 10)
              .map((e) => e.choice.toString())
              .toList();
```

I am currently using fuzzy search inside  **Search Delegate** flutter , but i don't think issue is through that as you'll see;

# Suggestions (choice list)

Sugesstions are my choices and its a large list :
```
[Test Title, YO, HELLO TITLE, Test title, Test title, Test title isha, Test title, Top 10 Highest Paying Jobs in India 2021, NEET Preparation Tips, Syllabus & Best Books for 2021, Best Books for JEE Preparation 2021, 2022, 2023 [Main + Advanced], Best Indian Romance Novels | A List of 10 Romantic Books, All the Harry Potter Books in Order: Your J.K. Rowling Reading List, Top 5 Sci Fi Books Ever Written Of All Time | Must Read, NEET PG 2021: Admit Card to be released on April 12. Check details, NTA Extends JEE Main 2021 April Application Correction Date - Check Details Here, TOP REASONS TO BUY SECOND HAND BOOKS ONLINE, KNOW HOW THE HABIT OF READING BOOKS CAN CHANGE YOUR LIFE!, Why to buy pre-loved books, This comic collector has one of the largest collections of vintage India-published comic books, As book publishing shrinks during the pandemic, how are India’s printing presses coping, Vikram Seth’s A Suitable Boy will soon stream on Netflix; here’s what the novel is all about, 10 Most Controversial Nov
```
## Remarks
> suggestions list have string with greater length - **I tried by using sub string of each string in suggestions , issue remained same**
> Also suggestion is of large length 

**Additional context**
> flutter doctor
```
F:\flutter_ecommerce_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
 Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1151], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.60.1)
[√] Connected device (3 available)

• No issues found!

```
> flutter doctor verbose
```
F:\Fluttter Apps\customer>flutter doctor -v
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1151], locale en-US)
    • Flutter version 2.5.0 at D:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (13 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\LAKHN KUMAWAT\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\LAKHN KUMAWAT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • RMX1851 (mobile) • 4e5981a2 • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!

```
> flutter version
```
F:\flutter_ecommerce_app>flutter --version
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (9 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0
```

@SphericalKat  Please help me if you get my issue 🥺.

**Comment by vjamrich** [comment] 2022-04-17 19:24
Same error here. I have around 300 000 choices. The issue goes away with a shorter choices list.

**Comment by sgehrman** [comment] 2022-06-12 03:39
I'm seeing this:

Error thrown by handler.
RangeError (index): Invalid value: Not in inclusive range 0..214: 216
dart:core                                                List.[]
DiffUtils.levEditDistance
package:fuzzywuzzy/diffutils/diff_utils.dart:600
DiffUtils.getRatio
package:fuzzywuzzy/diffutils/diff_utils.dart:732
SimpleRatio.apply
package:fuzzywuzzy/ratios/simple_ratio.dart:7
ratio
package:fuzzywuzzy/fuzzywuzzy.dart:14
WeightedRatio.apply
package:fuzzywuzzy/algorithms/weighted_ratio.dart:26
Extractor.extractWithoutOrder
package:fuzzywuzzy/extractor.dart:27
Extractor.extractSorted
package:fuzzywuzzy/extractor.dart:53
extractAllSorted

**Comment by vjamrich** [comment] 2022-07-07 13:03
> Hi ! I have the same error being thrown when I give a string with an emoji in it, could it be related ?

To expand on this, my dataset included chinese characters (UTF-8 encoding). Although taking a random subset of the dataset did not trigger the error - therefore I thought this might have been unrelated.

**Comment by SphericalKat** [comment] 2022-07-07 14:02
> Hi ! I have the same error being thrown when I give a string with an emoji in it, could it be related ?

Could you post your dataset if that's possible? If not; could you try removing any non-ascii characters from the dataset and see if it doesn't crash?

**Comment by SphericalKat** [comment] 2022-07-07 14:02
> > Hi ! I have the same error being thrown when I give a string with an emoji in it, could it be related ?
> 
> To expand on this, my dataset included chinese characters (UTF-8 encoding). Although taking a random subset of the dataset did not trigger the error - therefore I thought this might have been unrelated.
> 
> The dataset used consisted of the following dictionary - https://www.mdbg.net/chinese/dictionary?page=cedict

Thank you, I'll take a look with this.

**Comment by VuillaumeGautier** [comment] 2022-07-07 14:07
I don't have a dataset to give, as it's straight up test from a textfield : any emoji can make a crash, just removing it fix it.
I haven't tested chinese character, but japanese (and their chinese characters) seems to be fine on my side (it is just considered as a character, fuzziness still works fine).

**Comment by vimaxwell** [comment] 2022-11-17 05:48
I encounter same issue with this code
`ratio("🌙muộn màng là từ lúc - ca sĩ nguyên hà, lân nhã #inthemoonlight", "mỹ tâm - muộn màng là từ lúc")`

**Comment by woutervanwijk** [comment] 2023-02-02 10:55
Same here. It's a unicode problem maybe?

**Comment by Inakitajes** [comment] 2023-04-22 11:30
When does @SphericalKat will merge this fix?

**Comment by Kal-Elx** [comment] 2023-06-14 14:29
I can confirm that this is still a problem. @SphericalKat can you merge @seceba's suggestion?

**Comment by Kal-Elx** [comment] 2023-06-15 09:17
I created a PR with the changes suggested by @seceba and it works. Until it's merged you can use it by making this change in your pubspec.yaml.

```
fuzzywuzzy:
    # Use a fork where non ascii characters are handled.
    git:
      url: https://github.com/Kal-Elx/dart-fuzzywuzzy.git
      ref: fc70dd42f1d526ec3634af81598991173e272e09
```

**Comment by vjamrich** [comment] 2023-06-18 15:49
I can also confirm, the PR also fixed the issue on my side!

**Closed** 2023-06-18 16:50 UTC
Labels: bug
